import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

type HardhatArtifact = {
  abi: unknown[];
};

const payrollArtifactPath = join(
  process.cwd(),
  "artifacts",
  "contracts",
  "CipherRollPayroll.sol",
  "CipherRollPayroll.json"
);

const generatedAbiPath = join(
  process.cwd(),
  "web",
  "lib",
  "generated",
  "cipherroll-abi.ts"
);

function main() {
  const artifact = JSON.parse(
    readFileSync(payrollArtifactPath, "utf8")
  ) as HardhatArtifact;

  mkdirSync(join(process.cwd(), "web", "lib", "generated"), { recursive: true });

  const generatedSource = `// Auto-generated by \`npm run sync:interfaces\`.
// Do not edit this file by hand.

export const CIPHERROLL_ABI = ${JSON.stringify(artifact.abi, null, 2)} as const;

export type CiphertextHandle = \`0x\${string}\`;

export type CipherRollEncryptedInput = {
  ctHash: bigint | number | string;
  securityZone: number;
  utype: number;
  signature: \`0x\${string}\`;
};

export const ZERO_CIPHERTEXT_HANDLE = ${JSON.stringify(
    `0x${"0".repeat(64)}`
  )} as CiphertextHandle;
`;

  writeFileSync(generatedAbiPath, generatedSource);

  console.log(`Synced CipherRoll ABI to ${generatedAbiPath}`);
}

main();
